# fly.toml app configuration file generated for financial-funding-adviser-old-dawn-8062 on 2024-07-10T11:05:10-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'financial-funding-adviser-old-dawn-8062'
primary_region = 'bog'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
